---
- name: copy Dockerfile
  become_user: docker
  become: true
  template:
    src: Dockerfile.j2
    dest: /home/{{ docker_user }}/Dockerfile

- name: copy daemon.json
  become: true
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: restart docker service
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: log into Nexus docker registry
  become_user: docker
  become: true
  docker_login:
    registry: http://{{ nexus_server_ip }}:{{ nexus_server_docker_port }}
    username: "{{ maven_login }}"
    password: "{{ maven_password }}"
    reauthorize: yes

- name: build image and with build args and push to Nexus docker registry
  become_user: docker
  become: true
  docker_image:
    name: "{{ nexus_server_ip }}:{{ nexus_server_docker_port }}/javapp"
    #repository: "{{ nexus_server_ip }}:{{ nexus_server_docker_port }}/javapp"
    tag: "{{ build_number }}"
    push: yes
    build:
      path: /home/{{ docker_user }}/
      nocache: yes
      rm: yes
    source: build

- name: add tag latest to the last successfully built image
  become_user: docker
  become: true
  docker_image:
    name: "{{ nexus_server_ip }}:{{ nexus_server_docker_port }}/javapp:{{ build_number }}"
    repository: "{{ nexus_server_ip }}:{{ nexus_server_docker_port }}/javapp:latest"
    force_tag: yes
    push: yes
    state: present


# - name: build docker image
#   become_user: docker
#   become: true
#   command: "docker build -f /home/{{ docker_user }}/Dockerfile ."
