---
# defaults file for pavellucik.build_docker
nexus_server_ip: '172.31.46.242'
nexus_server_port: 8081
nexus_server_docker_port: 5000
maven_repository: maven-public1
maven_login: admin
maven_password: securepassword
maven_groupid: java
maven_artifactid: spring-boot-smoke-test-web-ui
maven_extention: jar

docker_group: docker
docker_user: docker
docker_image_name: javapp

javapp_service_port: 8080

build_number: "{{ lookup('file', '/var/lib/jenkins/build_number.txt', errors='warn') }}"
