---
- name: check if Docker is installed
  package_facts:
    manager: "auto"

- name: disable Docker service autostart
  service:
    name: docker
    enabled: no
  when: "'docker-ce' in ansible_facts.packages"
