---
- name: check if Docker is installed
  package_facts:
    manager: "auto"

- name: enable Docker service autostart
  service:
    name: docker
    enabled: yes
  when: "'docker-ce' in ansible_facts.packages"
