- name: Configure webserver with nginx
  hosts: webservers
  become: True
  tasks:
    - name: add epel-release repo
      yum:
        name: epel-release
        state: present
  
    - name: install nginx
      yum: name=nginx update_cache=yes
      
#    - name: copy nginx config file
#      copy: src=files/nginx.conf dest=/etc/nginx/conf.d/default
#    
#    - name: enable configuration
#      file: >
#        dest=/etc/nginx/conf.d/default.conf
#        src=/etc/nginx/conf.d/default
#        state=link
    
    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644
    
    - name: restart nginx
      service: name=nginx state=restarted
      